### ISSUE TITLE
面板提示 配置错误 获取Token失败

### ISSUE THREAD

**Issue by kfg81** [NolanHzy/nvjdcdocker#10]
我按照Readme进行安装，可以正常访问面板。
但是每次访问（包括刷新）都提示 “ 配置错误 获取Token失败”，config如下：

{
  ///浏览器最多几个网页
  "MaxTab": "4",
  //网站标题
  "Title": "qinglong",
  //回收时间分钟 不填默认3分钟
  "Closetime": "5",
  "AutoCaptchaCount": "5",
  //网站公告
  "Announcement": "本项目脚本收集于互联网。为了您的财产安全，请关闭京东免密支付。",
  ///青龙配置 注意 如果不要青龙  Config :[]
  "Config": [
    {
      //序号必填从1 开始
      "QLkey": 1,
      //服务器名称
      "QLName": "qinglong",
      //青龙地址
      "QLurl": "http://123.123.123.123:5700",
      //青龙2,9 OpenApi Client ID
      "QL_CLIENTID": "123123123",
      //青龙2,9 OpenApi Client Secret
      "QL_SECRET": "123123123",
      //CK最大数量
      "QL_CAPACITY": 40,
      "QRurl": ""
    }
  ]

}

请问是什么问题？谢谢

**Comment by Arui66** [comment]
//青龙2,9 OpenApi Client ID
"QL_CLIENTID": "123123123",
//青龙2,9 OpenApi Client Secret
"QL_SECRET": "123123123",
![image](https://user-images.githubusercontent.com/62711026/144095584-6a52883e-b021-4ef7-b681-012c64f45855.png)

**Comment by kip-lab** [comment]
+1

**Comment by geneyuriy** [comment]
填完token之后要重启一下容器 才生效
