### ISSUE TITLE
可以配置2个青龙容器吗

### ISSUE THREAD

**Issue by moonshine00** [NolanHzy/nvjdcdocker#15]
如何修改配置文件？谢谢

**Comment by BeiChenYi** [comment]
{
  ///浏览器最多几个网页
  "MaxTab": "4",
  //网站标题
  "Title": "NVJDC",
  //回收时间分钟 不填默认3分钟
  "Closetime": "3",
  //网站公告
  "Announcement": "XXXXXXXXXXXXXXX。",
  ///开启打印等待日志卡短信验证登陆 可开启 拿到日志群里回复 默认不要填写
  "Debug": "",
  ///自动滑块次数5次 5次后手动滑块 可设置为0默认手动滑块
  "AutoCaptchaCount": "5",
  ///XDD PLUS Url  http://IP地址:端口/api/login/smslogin
  "XDDurl": "",
  ///xddToken
  "XDDToken": "",
  ///青龙配置  注意对接XDD 对接芝士 设置为"Config":[]
  "Config": [
    {
      //序号必填从1 开始
      "QLkey": 1,
      //服务器名称
      "QLName": "阿里云",
      //青龙地址
      "QLurl": "",
      //青龙2,9 OpenApi Client ID
      "QL_CLIENTID": "",
      //青龙2,9 OpenApi Client Secret
      "QL_SECRET": "",
      //CK最大数量
      "QL_CAPACITY": 40,
      "QRurl": ""
    },
 {
      //序号必填从1 开始
      "QLkey": 2,
      //服务器名称
      "QLName": "阿里云",
      //青龙地址
      "QLurl": "",
      //青龙2,9 OpenApi Client ID
      "QL_CLIENTID": "",
      //青龙2,9 OpenApi Client Secret
      "QL_SECRET": "",
      //CK最大数量
      "QL_CAPACITY": 40,
      "QRurl": ""
    }
  ]
}
