### ISSUE TITLE
为什么啊。。。。。我json文件有问题？？

### ISSUE THREAD

**Issue by qiu-lzsnmb** [NolanHzy/nvjdcdocker#16]
![CAGN}D4D@R}(1@X@~{(Y5XN](https://user-images.githubusercontent.com/68412205/144695774-36125f2d-a5cc-4e64-ad9e-c57e2df92ea7.png)

**Comment by TurboJerry** [comment]
咱俩一样的错误,按照小姐姐教程一步一步来的
