### ISSUE TITLE
获取验证码的时候,发生报错One or more errors occurred. (Failed to launch browser! path to executable does not exist)

### ISSUE THREAD

**Issue by drophair** [NolanHzy/nvjdcdocker#23]
环境：
```
CPU: Amlogic S905
RAW: 1GB
ROM: 8GB
镜像版本: Linux aml 5.0.2-aml-s905 #5.77 SMP PREEMPT Mon Apr 1 17:41:33 MSK 2019 aarch64 GNU/Linux
```
操作：
输入手机号后，点击获取验证码后，产生报错
报错：
`One or more errors occurred. (Failed to launch browser! path to executable does not exist)`

**Comment by drophair** [comment]
查看输出的log显示,打开chrome窗口失败,如下是截取的一部分：
```
浏览器自检
-------------------------------------------------------------------------------------
arm！！！！！！！/usr/bin/chromium-browser
打开浏览器失败
Failed to launch browser! path to executable does not exist
-------------------------------------------------------------------------------------
```

**Comment by NolanHzy** [comment]
不认识英语么？ 按照流程下了浏览器了么？

**Comment by drophair** [comment]
根据[dpkgs.org](https://pkgs.org/download/chromium-browser),目前只有少数系统拥有chromium-browser安装包,目前包括官方和第三方的安装包只支持如下arm64系统`ATL Linux`, `OpenMandriva`, `openSUSE`, `Ubuntu`, 这么看来,对arm有需求的小伙伴可能需要转移至`Ubuntu 18.04 LTS`最为现实。使用`Armbian`, `Debian`, `Centos`的小伙伴除了[编译运行](https://www.cnblogs.com/zelos/p/5813465.html)以外是没有办法了.

**Comment by drophair** [comment]
> 不认识英语么？ 按照流程下了浏览器了么？

armbian下没有这个包，只能通过编译来安装，没必要了

**Comment by NolanHzy** [comment]
https://snapcraft.io/install/chromium/debian
