### ISSUE TITLE
arm搭好后有点问题呢？

### ISSUE THREAD

**Issue by Myxpx** [NolanHzy/nvjdcdocker#25]
访问是这样子![image](https://user-images.githubusercontent.com/87304369/145615362-da6e2165-e8b5-4206-97e9-1d7c64e8f1bc.png)

**Comment by drophair** [comment]
容器只是用来cv验证码的，你应该访问的是5701端口

**Comment by Myxpx** [comment]
好的好的，谢谢，反应有点慢开始5701进不去୧😂୨> 容器只是用来cv验证码的，你应该访问的是5701端口

**Comment by q123458384** [comment]
一样的问题-。-

**Comment by Myxpx** [comment]
把自动滑块次数设为0，就行了> The type initializer for 'Gdip' threw an exception.
> 
> 我是这个报错

**Comment by q123458384** [comment]
> 把自动滑块次数设为0，就行了> The type initializer for 'Gdip' threw an exception.
> 
> > 我是这个报错

没有设置选项呀-。-

**Comment by Myxpx** [comment]
config.json里面那个AutoCaptchaCount后面数学改为0> > 把自动滑块次数设为0，就行了> The type initializer for 'Gdip' threw an exception.
> 
> > 
> 
> > > 我是这个报错
> 
> 
> 
> 没有设置选项呀-。-

**Comment by Myxpx** [comment]
记得改好后重启若兰> > 把自动滑块次数设为0，就行了> The type initializer for 'Gdip' threw an exception.
> 
> > 
> 
> > > 我是这个报错
> 
> 
> 
> 没有设置选项呀-。-

**Comment by NolanHzy** [comment]
你看不懂英语么。却依赖装一下apt install libgdiplus
