### ISSUE TITLE
对接傻妞机器人有问题

### ISSUE THREAD

**Issue by swvv** [NolanHzy/nvjdcdocker#26]
![image](https://user-images.githubusercontent.com/25149246/145662496-2ffeedb0-da8f-4fb4-a82a-662a7c506953.png)
![image](https://user-images.githubusercontent.com/25149246/145662506-fa640d12-1dba-405e-aa0c-07da4bc2695e.png)

发送登录之后报错

**Comment by nzmd** [comment]
配置文件  "Config": [] 改成这个试试
![image](https://user-images.githubusercontent.com/21009810/145662806-b29c4f4b-e2f2-4fba-9d96-14ae5a3a58b9.png)

**Comment by swvv** [comment]
刚才青龙配置在config数组里，我现在拿到外面可以了。
![image](https://user-images.githubusercontent.com/25149246/145663111-c7d794f2-fbf6-43b7-a824-9e401b6164e9.png)
