### ISSUE TITLE
打开浏览器失败

### ISSUE THREAD

**Issue by Zbl1007** [NolanHzy/nvjdcdocker#27]
net::ERR_NAME_NOT_RESOLVED at https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D2087738584%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport at https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D2087738584%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport
请问log日志出现这个问题怎么解决

**Comment by drophair** [comment]
dns设置的问题，这类情况多见于公司学校的服务器(~~因为我也遇到了这样的问题,年轻人我劝你耗子尾汁~~)，如果是，~~可以和机房管理员进行进一步的沟通~~，家庭用户，可以检查dns的设置。
