### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by slippersheepig** [NolanHzy/nvjdcdocker#28]
首页标题能否居中显示，这样应该美观一点吧😂
![jd.png](https://img.sheepig.top/images/2021/12/12/jd.png)

**Comment by NolanHzy** [comment]
建议卸载

**Comment by slippersheepig** [comment]
好的，原来不能提建议啊，不好意思

**Comment by FKDXD** [comment]
> 好的，原来不能提建议啊，不好意思

有本事自己改去，说你妈呢

**Comment by slippersheepig** [comment]
这个人是谁呀，为啥那么嘴臭？我骂人了吗？
![jd2.png](https://img.sheepig.top/images/2021/12/12/jd2.png)
