### ISSUE TITLE
部分浏览器打开白屏（edge，手机自带浏览器，UC，QQ浏览器，alook）

### ISSUE THREAD

**Issue by DYS0327** [NolanHzy/nvjdcdocker#36]
部署成功后，部分浏览器可以正常打开（chrome，手机端via），部分浏览器打开白屏（edge，手机自带浏览器，UC，QQ浏览器，alook），并且均有提示We're sorry but XXX doesn't work properly without JavaScript enabled. Please enable it to continue.
控制台报错信息
![image](https://user-images.githubusercontent.com/55141555/146738282-2017923e-eda2-4e93-a838-b459329f23fc.png)

**Comment by itgoyo** [comment]
我这边今天在公司的电脑访问也出现了，昨晚家里的电脑还是好的。

**Comment by itgoyo** [comment]
时间：2021-12-20 17:50:42  现在打开已经正常

**Comment by itgoyo** [comment]
![](https://cdn.jsdelivr.net/gh/itgoyo/PicGoRes@master/img/20211220175446.png)
网站打开是可以了，但是获取手机验证码的时候出现了这个

**Comment by DYS0327** [comment]
> 时间：2021-12-20 17:50:42 现在打开已经正常

我的那几个浏览器打开还是白屏

**Comment by Fujjj** [comment]
更新一下就好了，git pull

**Comment by DYS0327** [comment]
> 更新一下就好了，git pull

刚更新了一下，确实好了，不过不清楚是什么原因，难道是上次git pull更新不彻底？

**Comment by Fujjj** [comment]
> > 更新一下就好了，git pull
> 
> 刚更新了一下，确实好了，不过不清楚是什么原因，难道是上次git pull更新不彻底？

昨天cdn挂了，作者把cdn去了，重新拉一下就好了，不是你的问题

**Comment by DYS0327** [comment]
> > > 更新一下就好了，git pull
> > 
> > 
> > 刚更新了一下，确实好了，不过是什么原因，难道是上次git pull更新不彻底？
> 
> 昨天cdn挂了，作者cdn去了，重拉一下就好了，不是你的问题

好的，谢谢
