### ISSUE TITLE
 System.ArgumentNullException: Value cannot be null. (Parameter 's')

### ISSUE THREAD

**Issue by zhangwenwu** [NolanHzy/nvjdcdocker#42]
System.ArgumentNullException: Value cannot be null. (Parameter 's') 啥情况呢

**Comment by zhangwenwu** [comment]
![image](https://user-images.githubusercontent.com/16423656/147332871-33d9507b-00ed-48bf-a049-4d78bf7f398c.png)

**Comment by zhangwenwu** [comment]
no

**Comment by CH-66** [comment]
我也是这个错误

**Comment by lplbb** [comment]
请问解决了吗
