### ISSUE TITLE
大佬，能否考虑增加自定义webhock配置呢？

### ISSUE THREAD

**Issue by ppaibb** [NolanHzy/nvjdcdocker#5]
即页面增加cookies 后将消息推送到指定URL ,有一个触发就好了。
谢谢。

**Comment by NolanHzy** [comment]
所以你想用什么API 去解决 七八种推送

**Comment by ppaibb** [comment]
> 所以你想用什么API 去解决 七八种推送

嗯，不需要适配他们呀，
做填空题就好了，请求头 请求方式 URl 请求体 这四个自己填写，
触发的时候就拿这四个发送请求。
这样做可以咩。

**Comment by NolanHzy** [comment]
可以是可以 但是我要是开了这个我就头疼了 邮件又满了。

**Comment by ppaibb** [comment]
> 可以是可以 但是我要是开了这个我就头疼了 邮件又满了。

嗯嗯 这么说也确实，徒增烦恼。
谢谢大佬了哈！~~
