### ISSUE TITLE
群晖的docker 不可以直接用么

### ISSUE THREAD

**Issue by 1029240203** [NolanHzy/nvjdcdocker#8]
![image](https://user-images.githubusercontent.com/74129503/143666228-f8d000ca-5434-42af-b36e-553b902f9d3f.png)
就这个  安装完后显示  启动错误 然后日志显示
![image](https://user-images.githubusercontent.com/74129503/143666241-84208f39-4d2c-4776-8899-bd5b7e2165ad.png)

**Comment by NolanHzy** [comment]
不看文档，你怎么好意思在这儿提问题？别用，

**Comment by lukemin** [comment]
要先git pull
